### PR TITLE
[WIP] Adding TabBarVC as initialVC

### PR DESCRIPTION
**Pull request by mohitathwani**
Implements #22

### CODE REVIEW

**Comment by kgellci** [comment]
is this ready to review?

**Comment by kgellci** [comment]
@mohitathwani ^

**Comment by mohitathwani** [comment]
What are the names for the tabs? I need to update the names.

Cheers !

--
Mohit Athwani
about.me/mohitathwani

**Comment by kgellci** [comment]
Hmm, probably call them posts and settings. Can update later if needed!

**Comment by kgellci** [comment]
Done in another PR, closing this for now. Feel free to make adjustments / changes and create a new PR.

**Pull request closed without merging**
