### PR TITLE
Add Unit Test Target

### PR DESCRIPTION
**Pull request by squarefrog**
As referenced in [this issue](https://github.com/kgellci/Area51/issues/27#issuecomment-467482944) I have no idea if this is the approach you are looking for, but its _an_ approach at least!

**Notes:**

- I have no idea what the difference between `Debug.xcconfig` and `area51-debug.xcconfig` is. I chose `Debug.xcconfig`. 

- Example tests now run while `Area51` target is set, and <kbd>CMD</kbd>+<kbd>U</kbd> pressed

- Ideally, the `window.rootViewController` in `AppDelegate` should be overridden when testing, to speed up tests somewhat further down the line.

- I have tested the target using `fastlane scan` and it executes the tests successfully, so there shouldn't be an issue setting this to run automatically on travis.

### CODE REVIEW

**Comment by kgellci** [comment]
Debug.xcconfig should be fine. Can you start by adding tests to Core instead of A51 target? I need to make some changes to A51 structure so the tests can live in the root target directory.  For core, you can add a Tests folder inside of Core: `Core/Tests`

You can then edit the Core.yml file to add the test target

```
targets:
  Core:
    type: library.static
    platform: iOS
    sources:
      - path: Sources
        name: Core
    settings:
      INFOPLIST_FILE: ../ModuleInfo.plist
    configFiles:
      Debug: ../Configs/Module.xcconfig
      Release: ../Configs/Module.xcconfig
  CoreTests:
    ...
```

An example: https://github.com/num42/RxUserDefaults/blob/master/project.yml

The only dependency that CoreTests should have is Core.  If you are really up for it, you can add some simple tests for the only file inside of Core!

**Comment by squarefrog** [comment]
OK done, and I've added that test. I should point out that stripping header or paragraph tags results in new lines. For example:

    "<h1>Foo</h1>".strippedHtml == "Foo\n"
    "<b>Bar</b>".strippedHtml == "Bar"

**Comment by squarefrog** [comment]
If we go this route (ie different test targets), it would probably be worth adding a run all tests function to the makefile.

**Comment by kgellci** [comment]
@squarefrog I will work on figuring that out, as well as making this run on CI

**Pull request merged**
